case/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', CaseListView.as_view(), name='home'),
	path('case/<int:pk>/',CaseDetailView.as_view(),name="case_detail" ),
	path('case/new/',CaseCreateView.as_view(),name="case_new" ),
	path('case/<int:pk>/edit/',CaseUpdateView.as_view(),name="case_edit" ),
	path('case/<int:pk>/delete/',CaseDeleteView.as_view(),name="case_delete" ),
	path('ajax/load_township/', load_township, name='ajax_load_township'),
]

yfcase/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("case.urls")),
]

case/models.py
from django.db import models
from django.urls import reverse

class Country(models.Model):
	name = models.CharField(verbose_name="縣市", max_length=50)
	
	def __str__(self):
		return self.name

class Township(models.Model):
	name = models.CharField(verbose_name="鄉鎮區", max_length=50)
	country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="縣市")
	
	def __str__(self):
		return self.name
		
class Case(models.Model):
	case_number = models.CharField(u'案號',max_length=100)
	country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, verbose_name="縣市")
	township = models.ForeignKey(Township, on_delete=models.SET_NULL, null=True, verbose_name="鄉鎮區")
	big_section = models.CharField(u'段號',max_length=100,blank=True,null=True)
	small_section = models.CharField(u'小段',max_length=100,blank=True,null=True)
	other_address = models.CharField(u'住址',max_length=100,blank=True,null=True)

	def __str__(self):
		return self.case_number

	def get_absolute_url(self):
		return reverse("case_detail",args={str(self.id)})
		
class Land(models.Model):
	case = models.ForeignKey(Case, on_delete=models.CASCADE, verbose_name="縣市")
	land_number = models.CharField(u'地號',max_length=100)
	land_url = models.CharField(u'地號謄本',max_length=100)
	land_area = models.DecimalField(u'地坪',max_digits=10,decimal_places=2)
	land_holding_point_personal = models.PositiveSmallIntegerField(default=0)
	land_holding_point_all = models.PositiveSmallIntegerField(default=0)

	def __str__(self):
		return self.land_number

case/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from .models import *

# COUNTRY_LIST= [
# 	('新北市', '新北市'),
# 	('台北市', '台北市'),
# 	('台中市', '台中市'),
# 	('台南市', '台南市'),
# 	('高雄市', '高雄市'),
# 	('屏東縣', '屏東縣')
# ]

class CaseForm(forms.ModelForm):
	# country = forms.ChoiceField(label='縣市',choices=COUNTRY_LIST)
	class Meta:
		model= Case
		fields='__all__'

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['township'].queryset = Township.objects.none()

		if 'country' in self.data:
			try:
				country_id = int(self.data.get('country'))
				self.fields['township'].queryset = Township.objects.filter(country_id=country_id).order_by('name')
			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty City queryset
		elif self.instance.pk:
			self.fields['township'].queryset = self.instance.country.township_set.order_by('name')
		self.helper = FormHelper()
		self.helper.layout = Layout(
			'case_number',
			Row(
				Column('country', css_class='form-group col-md-2 mb-0'),
				Column('township', css_class='form-group col-md-2 mb-0'),
				Column('big_section', css_class='form-group col-md-2 mb-0'),
				Column('small_section', css_class='form-group col-md-2 mb-0'),
				Column('other_address', css_class='form-group col-md-4 mb-0'),
				css_class='form-row'
			),
			Submit('submit', '新增', css_class='form-group col-md-2 mb-0')
		)

case/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import *

class CaseListView(ListView):
	model = Case
	template_name="case/case_list.html"

class CaseDetailView(DetailView):
	model=Case
	template_name="case/case_detail.html"

class CaseCreateView(CreateView):
	# model=Case
	template_name="case/case_new.html"
	form_class = CaseForm
	success_message = '建立成功'
	success_url = reverse_lazy('home')

class CaseUpdateView(UpdateView):
	model=Case
	fields='__all__'
	template_name='case/case_edit.html'

class CaseDeleteView(DeleteView):
	model=Case
	template_name="case/case_delete.html"
	success_url=reverse_lazy('home')
	
def load_township(request):
    country_id = request.GET.get('country')
    township = Township.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'case/city_dropdown_list_options.html', {'township': township})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-4.5.0.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-5.13.0-all.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro: " rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>

<body>
    <header>
        <div class="nav-left">
            <h1><a href="/">Djanog blog</a></h1>
        </div>
        <div class="nav-right">
            <a href="{% url 'case_new' %}">+ New Case</a>
        </div>
    </header>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'js/popper-1.16.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-4.5.0.min.js' %}"></script>
    <script src="{% static 'js/fontawesome-5.13.0-all.js' %}"></script>
</body>

</html>

templates/case/case_delete.html
{% extends "base.html" %}
{% block content %}
<h1>刪除評量表</h1>
<div class="post-entry">
	<form action="" method="post">{% csrf_token %}
		<p>你確定要刪除 "{{case.case_number}}" ?</p>
		<input type="submit" value="確認">
	</form>
</div>
{% endblock content %}

templates/case/case_detail.html
{% extends "../base.html" %}
{% block content %}
<h1>評量表明細</h1>
<div class="post-entry">
	<h2>{{object.case_number}}</h2>
	<p>{{object.country}}</p>
	<p>{{object.township}}</p>
	<p>{{object.big_section}}</p>
	<p>{{object.small_section}}</p>
	<p>{{object.other_address}}</p>
</div>
<a href="{% url 'case_edit' case.pk %}" class="btn btn-success btn-sm">+ Edit Case Post</a>
<a href="{% url 'case_delete' case.pk %}" class="btn btn-danger btn-sm">+ Delete Case Post</a>
{% endblock content %}

templates/case/case_edit.html
{% extends "base.html" %}
{% block content %}
<h1>更新評量表</h1>
<div class="post-entry">
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="更新" class="btn btn-primary">
	</form>
</div>
{% endblock content %}

templates/case/case_list.html
{% extends "../base.html" %}
{% block content %}
	<h1>評量表清單</h1>
	<table class="table">
		<thead class="bg-dark text-light">
			<tr>
				<th>案號</th>
				<th>縣市</th>
				<th>鄉鎮區</th>
				<th>段號</th>
				<th>小段</th>
				<th>住址</th>
			</tr>
		</thead>
		<tbody>
			{% for obj in object_list %}
				<tr>
					<td><a href="{% url 'case_detail' obj.pk %}">{{ obj.case_number }}</a></td>
					<td>{{ obj.country }}</td>
					<td>{{ obj.township }}</td>
					<td>{{ obj.big_section }}</td>
					<td>{{ obj.small_section }}</td>
					<td>{{ obj.other_address }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}

templates/case/case_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>建立評量表</h1>
<div class="post-entry">
	<form action="" method="post" id="CaseForm" data-township-url="{% url 'ajax_load_township' %}" novalidate>{% csrf_token %}
		{% crispy form %}
	</form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_country").change(function () {
  // get the url of the `load_cities` view
  var url = $("#CaseForm").attr("data-township-url");  
  // get the selected country ID from the HTML input
  var countryId = $(this).val();  
  
  // initialize an AJAX request
  $.ajax({   
    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)                    
    url: url,                    
    data: {
      // add the country id to the GET parameters
      'country': countryId       
    },
    // `data` is the return of the `load_cities` view function
    success: function (data) {   
      // replace the contents of the city input with the data that came from the server
      $("#id_township").html(data);  
    }
  });

});
</script>

{% endblock content %}

templates/case/city_dropdown_list_options.html
<option value="">---------</option>
{% for ts in township %}
<option value="{{ ts.pk }}">{{ ts.name }}</option>
{% endfor %}